### PR TITLE
Organize/rename fundraising templates

### PR DESCRIPTION
**Pull request by aisapatino**
@tarhata I got really sidetracked from whatever I was doing and decided to organize the templates for the fundraising side of the app. What do you think? Questions/suggestions?

- `/emails` is for email templates, used mostly by cron jobs
- `/forms` is for templates that just contain a form, maybe with a wrapper (`<div>` element) around it. Usually `include`d or loaded via ajax request
- `/includes` is for non-form snippets that are included into other templates, but not used on their own. For instance, `includes/donor_details.html` is used inside a for loop in `fund/home.html` to display info for each donor.
- `/scripts` is for templates with a `<script>` tag inside that are `include`d by other templates. Currently only one (that I just split up from `home.html`) but I might break out some others in an attempt to make things more readable.
- Names prefixed with an underscore, like `_base.html` are base templates that are `extend`ed by other templates.
- Aside from that, I renamed some templates where I thought the previous name was unclear or inconsistent with the overall naming patterns. For example, `add_mult_flex` -> `add_contacts`

```
├── emails
│   ├── account_approved.html
│   ├── accounts_need_approval.html
│   ├── gift_received.html
│   ├── overdue_steps.html
│   └── reset_password.html
├── forms
│   ├── add_contacts.html
│   ├── add_estimates.html
│   ├── add_mult_step.html
│   ├── add_step.html
│   ├── complete_step.html
│   ├── copy_contacts.html
│   ├── delete_contact.html
│   ├── edit_contact.html
│   ├── edit_step.html
│   └── gp_survey.html
├── includes
│   ├── donor_details.html
│   ├── footer.html
│   └── suggested_steps.html
├── scripts
│   └── home_charts.html
├── account_projects.html
├── _base_blocks.html
├── _base.html
├── _base_personal.html
├── blocked.html
├── grants.html
├── home.html
├── login.html
├── not_approved.html
├── not_member.html
├── project.html
├── registered.html
├── register.html
├── reset_password_complete.html
├── reset_password.html
├── reset_password_sent.html
├── reset_password_start.html
└── support.html
```

### CODE REVIEW

**Comment by tarhata** [comment]
Haha, I'm glad I don't have to worry about you leaving the the development of PC!

Your file structure seems to make sense, though I'm still unclear about the `\includes` thing. I'm still looking at the old code before the merge and can't find `donor_details.html`, so maybe it'll make sense once it's all up to date.

I'm guessing the templates in the root folder are ones which are tied to "main" views (not sure if there's a word for that), right? Like, `project.html` which doesn't have fancy javascript or AJAX stuff. 
project html screen

Hope I'm using the right jargon...so much still to learn! That markdown thing is pretty cool :) I always wondered how people did that!

**Comment by aisapatino** [comment]
Oh, I renamed that file as well as moving it. It was `_donor.html` before. In the [Files changed](https://github.com/aisapatino/sjfnw/pull/729/files) tab, you can see file renames in the title bars (although there are so many changes in this PR I had to search for it)

Yep, that's correct :) The idea is for whatever's left in the main directory (except for the underscored base ones) to be templates that are rendered directly - the ones named in the view methods:

 `return render(response, 'project.html', ...`

`/includes` is for re-usable snippets that are meant to be included into other templates via the `include` tag. If you look at [includes/donor_details.html](https://github.com/aisapatino/sjfnw/blob/templates-organizing/sjfnw/templates/fund/includes/donor_details.html), it's just a big `<div>` element. It has a lot of variables - a template loaded via `include` gets all the variables from its parent template. Before, all of that was inside the `home.html` template, but it's a very long, nested and complicated template, so I split it up to simplify it. `includes/suggested_steps.html` is there because it's used in several different forms and now they can share that template instead of copying the same code.

Does that make any more sense? We can also talk about it tomorrow if that's helpful. The multiple methods of nesting/sharing templates is not the most intuitive. But the flexibility does come in handy.

And yes markdown is awesome! Did you know it has built in emoji? http://www.emoji-cheat-sheet.com/

:octocat:

**Comment by aisapatino** [comment]
Did a search on all the `include` and `extends` tags as well as all the `render` calls in `sjfnw/fund/views.py` - found one incorrect filename, otherwise looks good. Merging; we can always revise as we see fit.

**Comment by tarhata** [comment]
Yup, know about the emojis -- was just too lazy to look it up :smile: 

Is codecov the same as coveralls? Just curious why the switch.

I pulled `master` and compared the new file structure to the old one and like it a lot better. Definitely makes it easier to find files and know what's related to what and what's reused. Plus, it's just DRY that way :grin:

**Comment by aisapatino** [comment]
They are similar services, the reason I changed is that codecov does [branch coverage](http://stackoverflow.com/questions/8229236/differences-between-line-and-branch-coverage) as well as the basic statement coverage. For instance, take a look at the most recent results for [`sjfnw/fund/cron.py`](https://codecov.io/github/aisapatino/sjfnw/sjfnw/fund/cron.py?ref=master#67). The yellow highlight shows that we haven't tested what happens if `if to_emails:` is not satisfied and we don't enter that branch of the code. Statement coverage alone would show that we covered that whole section.

Not a big deal since we're not nitpicking coverage at this point (given that we have a ways to go), but still nice to have more information.

**Pull request merged**
